-- =====================================================================
-- Seed : 29 prospects LinkedIn (campagne cabinets comptables - mai 2026)
-- Idempotent : on s'appuie sur la colonne unique "numero".
-- =====================================================================

insert into public.prospects
  (numero, date_envoi, prenom, nom, poste, societe, zone_geographique,
   niveau_relation, angle_message, message_envoye,
   connexion_acceptee, date_acceptation, date_followup_prevue,
   followup_envoye, reponse, type_reponse, rdv_programme, notes)
values
  (1,  '2026-05-04', 'Céline',    'M.',              'Associée',                        'Groupe Archipel',                       'Conflans-Sainte-Honorine, IDF', '3e', 'Cabinet généraliste',            'Bonjour Céline, ingénieur Arts et Métiers spécialisé IA, Tech Lead en scale-up européenne. J''aide les cabinets comptables comme Groupe Archipel à automatiser certains process avec de l''IA (tri d''emails, qualification de leads, courriers récurrents)...', 'À compléter', null, null, false, null, null, false, 'Envoyé lundi - À vérifier acceptation'),
  (2,  '2026-05-04', 'Delphine',  'Meheut',          'Associée',                        'ACL',                                   'Paris et périphérie',           '3e', 'Cabinet généraliste',            'Bonjour Delphine, Tech Lead spécialisé IA (ingénieur Arts et Métiers, scale-up européenne). J''accompagne les cabinets comme ACL sur l''automatisation IA...', 'À compléter', null, null, false, null, null, false, 'Envoyé lundi - À vérifier acceptation'),
  (3,  '2026-05-04', 'Marc',      'MANCINI',         'Associé',                         'In Extenso Ile-de-France',              'Lisses, IDF',                   '3e', 'Multi-sites',                    'Bonjour Marc, ingénieur Arts et Métiers spécialisé IA, Tech Lead en scale-up européenne. J''aide les cabinets comme In Extenso IDF à automatiser certains process avec l''IA...', 'À compléter', null, null, false, null, null, false, 'Envoyé lundi - À vérifier acceptation'),
  (4,  '2026-05-04', 'Catherine', 'Carre-Homage',    'Partner',                         'VISEA consulting',                      'Paris et périphérie',           '3e', 'Cabinet conseil',                'Bonjour Catherine, Tech Lead spécialisé IA (Arts et Métiers, scale-up européenne). Je travaille avec des cabinets comme VISEA Consulting pour automatiser certains process avec l''IA...', 'À compléter', null, null, false, null, null, false, 'Envoyé lundi - À vérifier acceptation'),
  (5,  '2026-05-04', 'Estelle',   'Theret',          'Présidente',                      'Sillage Experts',                       'Paris, IDF',                    '2e', 'Dirigeante',                     'Bonjour Estelle, ingénieur Arts et Métiers spécialisé IA, Tech Lead en scale-up européenne. J''aide les cabinets comme Sillage Experts à automatiser certains process avec l''IA...', 'À compléter', null, null, false, null, null, false, 'Envoyé lundi - À vérifier acceptation'),
  (6,  '2026-05-05', 'Edouard',   'Nieuwjaer',       'Directeur',                       'IMPULSA',                               'Paris, IDF',                    '3e', 'ROI chiffré',                    'Bonjour Edouard, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme IMPULSA à automatiser certains process (tri emails, qualification leads, courriers récurrents) — typiquement 4-6h gagnées par semaine...', 'À compléter', null, null, false, null, null, false, null),
  (7,  '2026-05-05', 'Nathalie',  'Marquant',        'Directrice Pôle Comptabilité',    'ECODIA MARQUANT',                       'France',                        '3e', 'Facturation électronique',       'Bonjour Nathalie, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les pôles comptabilité comme celui d''Ecodia à automatiser certains process (tri emails, courriers récurrents) — utile en pré-réforme facturation électronique...', 'À compléter', null, null, false, null, null, false, null),
  (8,  '2026-05-05', 'Emmanuel',  'Dupeux',          'Global Board Director',           'Russell Bedford International',         'Paris, IDF',                    '3e', 'International',                  'Bonjour Emmanuel, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Russell Bedford à industrialiser l''IA dans leurs process opérationnels...', 'À compléter', null, null, false, null, null, false, null),
  (9,  '2026-05-05', 'Marc',      'Chezot',          'Partner',                         'Aditec / Compta 7',                     'Paris, IDF',                    '1er','ROI chiffré',                    'Bonjour Marc, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Aditec à automatiser certains process — gain typique de 4-6h par semaine et par collaborateur...', 'OUI',          null, null, false, null, null, false, 'Relation 1er niveau - message déjà envoyé'),
  (10, '2026-05-05', 'Fabrice',   'VIDAL',           'Directeur général',               'CADERAS MARTIN',                        'Paris, IDF',                    '3e', 'DG production',                  'Bonjour Fabrice, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les DG de cabinets comptables comme Caderas Martin à industrialiser l''IA dans leurs process...', 'À compléter', null, null, false, null, null, false, null),
  (11, '2026-05-05', 'Clément',   'FLOC''H',         'Director',                        'Europartner',                           'Paris et périphérie',           '3e', 'Question ouverte',               'Bonjour Clément, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Europartner à automatiser certains process. Vous explorez ces sujets actuellement ?', 'À compléter', null, null, false, null, null, false, null),
  (12, '2026-05-05', 'Alexandra', 'Pestel',          'Associée',                        'AUDIXIA',                               'Paris et périphérie',           '3e', 'Sobriété',                       'Bonjour Alexandra, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme AUDIXIA à automatiser leurs process opérationnels...', 'À compléter', null, null, false, null, null, false, null),
  (13, '2026-05-05', 'Avner',     null,              'Partner',                         'ACL',                                   'Paris et périphérie',           null, 'Facturation électronique',       'Bonjour Avner, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme ACL à automatiser certains process...', 'À compléter', null, null, false, null, null, false, 'Différer Benjamin (autre partner ACL) de 15-20 jours'),
  (14, '2026-05-05', 'Jonathan',  'Benford',         'Partner',                         'Benford Lemaître',                      'Paris et périphérie',           '2e', 'ROI chiffré',                    'Bonjour Jonathan, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Benford Lemaître à automatiser certains process — gain typique de 4-6h par semaine...', 'À compléter', null, null, false, null, null, false, null),
  (15, '2026-05-05', 'Karine',    'Jolivet',         'Director',                        'COGEED',                                'Paris, IDF',                    '3e', 'Question ouverte',               'Bonjour Karine, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme COGEED à automatiser certains process. Vous explorez ces sujets actuellement chez COGEED ?', 'À compléter', null, null, false, null, null, false, null),
  (16, '2026-05-06', 'Vanessa',   'Ferreira',        'Élue',                            'CRCC de Paris',                         'Ormesson-sur-Marne, IDF',       '2e', 'Institutionnel humble',          'Bonjour Vanessa, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''accompagne des cabinets et CAC sur l''industrialisation de l''IA en production. Vous explorez ces sujets actuellement ?', 'À compléter', null, null, false, null, null, false, 'Institutionnel - approche humble'),
  (17, '2026-05-06', 'Marine',    'BRIAND',          'VP Ordre Paris IDF',              'Ordre des experts-comptables Paris IDF','Paris et périphérie',           '1er','Institutionnel humble',          'Bonjour Marine, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide des cabinets à industrialiser l''IA dans leur production (pré-saisie, révision, conseil client). Vous explorez ces sujets actuellement ?', 'OUI',          null, null, false, null, null, false, 'Relation 1er niveau - VP Ordre IDF (asset majeur)'),
  (18, '2026-05-06', 'Nicolas',   'Lopez',           'Dirigeant',                       'AUDIT CONSULTING GROUP',                'Paris, IDF',                    '2e', 'DG production',                  'Bonjour Nicolas, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les dirigeants de cabinets comme Audit Consulting Group à industrialiser l''IA en production...', 'À compléter', null, null, false, null, null, false, null),
  (19, '2026-05-06', 'Clémence',  'Bonadé',          'Associée',                        'Coffra group',                          'France',                        '1er','Facturation électronique',       'Bonjour Clémence, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Coffra Group à industrialiser l''IA en production : pré-saisie comptable automatisée...', 'OUI',          null, null, false, null, null, false, 'Relation 1er niveau - message déjà envoyé'),
  (20, '2026-05-06', 'Benjamin',  'Tixier',          'Partner',                         'Crowe HAF',                             'Paris et périphérie',           '3e', 'Conseil client',                 'Bonjour Benjamin, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Crowe HAF à libérer du temps de production pour redéployer leurs équipes sur du conseil client...', 'À compléter', null, null, false, null, null, false, null),
  (21, '2026-05-06', 'Thierry',   'Bretout',         'Owner',                           'RBB International',                     'Paris et périphérie',           '1er','Veille réglementaire',           'Bonjour Thierry, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme RBB International à automatiser leur veille fiscale et réglementaire...', 'OUI',          null, null, false, null, null, false, 'Relation 1er niveau - message déjà envoyé'),
  (22, '2026-05-06', 'Arthur',    'Zimmer',          'Partner',                         'Ecovis France',                         'Paris, IDF',                    '2e', 'Production multi-cas',           'Bonjour Arthur, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Ecovis France à industrialiser l''IA sur leurs process à fort enjeu...', 'À compléter', null, null, false, null, null, false, null),
  (23, '2026-05-06', 'Juliette',  'Chantereau',      'Associée',                        'Apsis Audit',                           'Paris, IDF',                    '3e', 'Facturation électronique + question','Bonjour Juliette, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les cabinets comme Apsis Audit à industrialiser l''IA en production : pré-saisie comptable et préparation de la facturation électronique 2026. Vous explorez ces sujets actuellement ?', 'À compléter', null, null, false, null, null, false, null),
  (24, '2026-05-06', 'Silvia',    'Létang',          'Chief Financial Officer',         'TGS',                                   'Paris et périphérie',           '1er','CFO production',                 'Bonjour Silvia, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''accompagne des CFO comme vous sur l''industrialisation de l''IA dans la production financière...', 'À compléter', null, null, false, null, null, false, 'Relation 1er niveau - message déjà envoyé'),
  (25, '2026-05-06', 'Didier',    'Emerique',        'Propriétaire',                    'AGEX',                                  'Voisins-le-Bretonneux, IDF',    '3e', 'Dirigeant TPE',                  'Bonjour Didier, ingénieur Arts et Métiers, Tech Lead IA en scale-up. J''aide les dirigeants de cabinets comme AGEX à libérer du temps de production pour développer le conseil client...', 'À compléter', null, null, false, null, null, false, null),
  (26, null,         'Marie',     'BOUVIER DAUCHY',  'Directrice',                      'Groupe Rey',                            'France',                        '3e', null,                             null, null, null, null, false, null, null, false, 'Date envoi à confirmer'),
  (27, null,         'Patricia',  'DURET',           'Associée',                        null,                                    'Paris et périphérie',           '2e', null,                             null, null, null, null, false, null, null, false, 'Société à compléter'),
  (28, null,         'Mathias',   'Benarosch',       'Partner',                         'EKEM Partners',                         'Paris et périphérie',           '3e', null,                             null, null, null, null, false, null, null, false, 'Date envoi à confirmer'),
  (29, null,         'Hugo',      'GARROS',          'Partner',                         'ACL',                                   'Paris et périphérie',           '3e', null,                             '3e partner ACL — attention pattern, différer', null, null, null, false, null, null, false, 'ATTENTION : 3e contact ACL après Avner et Delphine')
on conflict (numero) do update set
  date_envoi           = excluded.date_envoi,
  prenom               = excluded.prenom,
  nom                  = excluded.nom,
  poste                = excluded.poste,
  societe              = excluded.societe,
  zone_geographique    = excluded.zone_geographique,
  niveau_relation      = excluded.niveau_relation,
  angle_message        = excluded.angle_message,
  message_envoye       = excluded.message_envoye,
  connexion_acceptee   = excluded.connexion_acceptee,
  notes                = excluded.notes,
  updated_at           = now();
